name: publish npm package

on:
    push:
        branches: [master, main]
jobs:
    auto_release_npm_package:
        uses: https://raw.githubusercontent.com/daichangxin/github-config/master/github-ci/auto_release_npm_package.yml
